/** Barrel del motore di Price — funzioni pure, testabili, senza DOM. */
export * from './types'
export * from './codes'
export * from './pack'
export * from './legacy-xlsx'
export * from '../../../shared/compositore/tematiche'
export * from '../../../shared/compositore/macrocategorie'
export * from '../../../shared/compositore/thesaurus'
export * from './search'
export * from './analisi-import'
export * from './suggest'
export * from './conduits'
export * from './cables'
export * from './descriptions'
export * from '../../../shared/compositore/componi'
export * from '../../../shared/compositore/libreria'
export * from '../../../shared/compositore/datasheet'
export * from '../../../shared/compositore/datasheet-profili'
export * from '../../../shared/compositore/marchi'
export * from '../../../shared/compositore/analisi-prezzi'
export * from '../../../shared/compositore/misurazioni'
// Fase 2 (edizione server) — un solo await all'avvio per marchi/libreria/sinonimi.
// Voci studio (edizione server): libreria condivisa per azienda, terzo livello
// oltre a curate/tue.
export * from './report'
export * from './analisi-prezzi-report'
export * from './analisi-prezzi-excel'
export * from './computo-excel'
export * from './categorie-db'
export * from './parsers/metel'
